package org.buffer.android.reactiveplaybilling

enum class BillingResult {
    BILLING_UNAVAILABLE, DEVELOPER_ERROR, ERROR, FEATURE_NOT_SUPPORTED, ITEM_ALREADY_OWNED,
    ITEM_NOT_OWNED, ITEM_UNAVAILABLE, OK, SERVICE_DISCONNECTED, SERVICE_UNAVAILABLE, USER_CANCELED
}